# Generated by Django 4.2.5 on 2023-10-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id',
                 models.BigAutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('full_name',
                 models.CharField(
                     max_length=150,
                     verbose_name='Полное имя')),
                ('description',
                 models.CharField(
                     max_length=150,
                     verbose_name='Описание')),
                ('img',
                 models.ImageField(
                     upload_to='',
                     verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
