# Generated by Django 4.2.5 on 2023-10-04 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='img',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to='',
                verbose_name='Фото'),
        ),
    ]
