# Generated by Django 4.2.5 on 2023-09-27 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id',
                 models.BigAutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('category_doctor',
                 models.CharField(
                     max_length=100,
                     verbose_name='Категория доктора')),
                ('full_name',
                 models.CharField(
                     blank=True,
                     max_length=100,
                     null=True,
                     verbose_name='Имя доктора')),
                ('description',
                 models.TextField(
                     verbose_name='Описание')),
                ('image',
                 models.ImageField(
                     blank=True,
                     null=True,
                     upload_to='',
                     verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Доктор',
                'verbose_name_plural': 'Доктора',
            },
        ),
    ]
